---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: task-management-system-local
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/overlays/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: task-management-system
  timeout: 3m0s
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: users-service
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: logout-service
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: mysql
      namespace: tms-app
