apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: tms-app
type: Opaque
stringData:
  password: "rootpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-username
  namespace: tms-app
type: Opaque
stringData:
  username: "taskuser"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-name
  namespace: tms-app
type: Opaque
stringData:
  name: "task_management"
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-endpoint
  namespace: tms-app
type: Opaque
stringData:
  endpoint: "mysql-service"
