apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tms-app

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - users-deployment.yaml
  - users-service.yaml
  - logout-deployment.yaml
  - logout-service.yaml
  - mysql-configmap.yaml

commonLabels:
  app.kubernetes.io/name: task-management-system
  app.kubernetes.io/managed-by: kustomize
