---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: tms-app
  labels:
    app: auth-service
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: task-service-monitor
  namespace: tms-app
  labels:
    app: task-service
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: task-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: tms-app
  labels:
    app: frontend
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
