---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: task-management-system-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: task-management-system
  timeout: 5m0s
  wait: true
  retryInterval: 2m0s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: users-service
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: logout-service
      namespace: tms-app
    - apiVersion: apps/v1
      kind: Deployment
      name: mysql
      namespace: tms-app
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
